resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - daemonset.yaml
  - service.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
configMapGenerator:
  - name: kube-network-monitor-dashboard
    namespace: kube-system
    files:
      - kube-network-monitor-dashboard.json
generatorOptions:
  disableNameSuffixHash: true
