apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-network-monitor
  namespace: kube-system
  labels:
    app: kube-network-monitor
spec:
  groups:
    - name: kube-network-monitor
      rules:
        - alert: NetworkMonitorNodeUnreachable
          annotations:
            description: The node {{ $labels.target }} is unreachable from the node {{ $labels.source }}.
            summary: Node is {{ $labels.target }} unreachable.
          expr: min by (source, target) (network_monitor_reachable) == 0
          labels:
            severity: critical
        - alert: NetworkMonitorPacketLoss
          annotations:
            description: Between the node {{ $labels.source }} and {{ $labels.target }} there is packet loss.
            summary: Packet loss between {{ $labels.source }} and {{ $labels.target }}.
          for: 1m
          expr: max by (source, target) (rate(network_monitor_packets_lost[5m]) / rate(network_monitor_packets_sent[5m])) > 0
          labels:
            severity: critical
