name: test
on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - main
env:
  GO111MODULE: on
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - uses: actions/checkout@v2
    - name: Install binaries
      run: |
        mkdir /opt/goreleaser
        cd /opt/goreleaser
        curl -fsSL https://github.com/goreleaser/goreleaser/releases/download/v1.18.2/goreleaser_Linux_x86_64.tar.gz | tar xz
        chmod +x goreleaser
        echo "/opt/goreleaser" >> $GITHUB_PATH
        mkdir /opt/kind
        cd /opt/kind
        curl -fsSL https://kind.sigs.k8s.io/dl/v0.19.0/kind-linux-amd64 > kind
        chmod +x kind
        echo "/opt/kind" >> $GITHUB_PATH
    - name: Build sources
      run: go build ./...
    - name: Run tests
      run: make test
    - name: Run tests e2e
      run: make test-e2e
