name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  GO111MODULE: on
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: 1.22.x
    - uses: actions/checkout@v4
    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        install-only: true
    - name: Install kind
      run: |
        mkdir /opt/kind
        cd /opt/kind
        curl -fsSL https://kind.sigs.k8s.io/dl/v0.19.0/kind-linux-amd64 > kind
        chmod +x kind
        echo "/opt/kind" >> $GITHUB_PATH
    - name: Build sources
      run: go build ./...
    - name: Run tests
      run: make test
    - name: Run tests e2e
      run: make test-e2e
